# Sign Up

The course will be held on **January 16-19, 2023 at 5:30-7:30pm NPT**, via Zoom. The time of the course was determined by the most popular time slot in the sign up form. The final day to sign up will be <span style="color: #FF7733;">**extended to January 13, 2023**</span>.

* **Everyone: Please fill out your [sign up form](https://forms.gle/8mtKdmmti24CjbAU8){target="_blank"}.** This sign-up includes a photo/video waiver. The workshops will be recorded to help with future learning. Some stills from the sessions may be used for future marketing.

* **Everyone: Please fill out your [introductory form](https://forms.gle/Ch3S97guJhF9dYYT9){target="_blank"}.** This is to gauge participants' interests and the workshops' effectiveness. This form is anonymous, but critical to our ability to offer courses in the future. Thank you.

* **Everyone: Ensure you are able to log onto Zoom.** Your calendar hold with the Zoom link will be in your inbox shortly.

* <span style="color: #FF7733;">**Technical sessions ONLY**</span>**: Sign up for [Google Earth Engine](https://earthengine.google.com/signup/){target="_blank"}.** Please do this as soon as possible! Sometimes it takes longer than expected to go through. Signing up for Google Earth Engine is free and **requires a Google account**. Instructions can be found in the [Google Earth Engine Section](https://woodwellrisk.github.io/Nepal_Workshops/google-earth-engine.html) of this website. Consider creating it "For myself", if you don't already have an account. 

* **For those not comfortable in English: Consider downloading the General Session slideshow .pdf (coming soon).** The speaker's notes are written out in English as a form of subtitles. There will also be Nepali speakers on the call who can translate.
